language: php

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - MONGO_EXTENSION="mongodb.so"
    - COMPOSER_FLAGS=""
    - DB=pdo_mysql
    - DB_USER=root
    - DB_NAME=lexik_test

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION="lts:^2"
    - php: 7.1
      env: SYMFONY_VERSION="lts:^3"
  fast_finish: true

services:
    - mongodb
    - mysql

before_install:
  - echo "extension = $MONGO_EXTENSION" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer config platform.ext-mongo 1.6.16
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/${SYMFONY_VERSION}" --no-update; fi;
  - if ! [[ $TRAVIS_PHP_VERSION =~ ^5 ]]; then composer require alcaeus/mongo-php-adapter --no-update; fi;
  - set -ev
  - sh -c "if [ '$DB' = 'pdo_mysql' ]; then mysql -e 'create database IF NOT EXISTS $DB_NAME' -u$DB_USER; fi"

  - |
    # php.ini configuration
    for PHP in $TRAVIS_PHP_VERSION $php_extra; do
        phpenv global $PHP 2>/dev/null || (cd / && wget https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/16.04/x86_64/php-$PHP.tar.bz2 -O - | tar -xj)
        INI=~/.phpenv/versions/$PHP/etc/conf.d/travis.ini
        echo date.timezone = Europe/Paris >> $INI
        echo memory_limit = -1 >> $INI
        echo session.gc_probability = 0 >> $INI
        echo opcache.enable_cli = 1 >> $INI
        echo apc.enable_cli = 1 >> $INI
        echo extension = memcached.so >> $INI
    done

install: composer update --no-interaction

script:
    - php vendor/bin/phpunit --coverage-text
