language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - MONGO_EXTENSION="mongodb.so"
    - COMPOSER_FLAGS=""

matrix:
  include:
    - php: 5.6
      env: MONGO_EXTENSION="mongo.so" SYMFONY_VERSION="symfony/lts:^2" DB=pdo_mysql DB_USER=root DB_NAME=lexik_test
    - php: 7.1
      env: SYMFONY_VERSION="symfony/lts:^3" DB=pdo_mysql DB_USER=root DB_NAME=lexik_test
  fast_finish: true

services:
    - mongodb
    - mysql

before_install:
    - echo "extension = $MONGO_EXTENSION" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - composer config platform.ext-mongo 1.6.16
  - if [ "$SYMFONY_VERSION" != "" ]; then travis_wait composer require --no-update $SYMFONY_VERSION; fi;
  - travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
  - if ! [[ $TRAVIS_PHP_VERSION =~ ^5 ]]; then composer require alcaeus/mongo-php-adapter; fi;

install:
    - if [ -x .travis/install.sh ]; then .travis/install.sh; fi;

script:
    - php vendor/bin/phpunit -v
