language: php

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - MONGO_EXTENSION="mongodb.so"
    - COMPOSER_FLAGS=""

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION="lts:^2" DB=pdo_mysql DB_USER=root DB_NAME=lexik_test
    - php: 7.1
      env: SYMFONY_VERSION="lts:^3" DB=pdo_mysql DB_USER=root DB_NAME=lexik_test
  fast_finish: true

services:
    - mongodb
    - mysql

before_install:
  - echo "extension = $MONGO_EXTENSION" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer config platform.ext-mongo 1.6.16
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/${SYMFONY_VERSION}" --no-update; fi;
  - if ! [[ $TRAVIS_PHP_VERSION =~ ^5 ]]; then composer require alcaeus/mongo-php-adapter --no-update; fi;

install: composer update --no-interaction

script:
    - php vendor/bin/phpunit --coverage-text
